# Generated by Django 4.1.2 on 2022-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('phone_number', models.TextField()),
                ('phone_number_verified', models.BooleanField()),
                ('user_avatar', models.TextField()),
                ('clan_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=128)),
            ],
        ),
    ]
