# Generated by Django 4.1.2 on 2022-10-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_usere'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usere',
            new_name='Useere',
        ),
    ]
