# Generated by Django 4.1.2 on 2022-10-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_usere_useere'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Useere',
            new_name='User',
        ),
    ]
