# Generated by Django 4.1.2 on 2022-10-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.TextField(default='https://cdn-icons-png.flaticon.com/512/1160/1160040.png?w=360'),
        ),
    ]
