# Generated by Django 4.1.3 on 2022-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_clan_id_alter_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
