# Generated by Django 4.1.3 on 2022-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_token_user_token_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
