# Generated by Django 4.1.3 on 2022-11-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='token',
            field=models.TextField(default='fff000', unique=True),
            preserve_default=False,
        ),
    ]
