name: "Push: main"

on:
  push:
    branches:    
      - 'main'

permissions: write-all

jobs:
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
    needs: [ ci ]
  release_draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
    needs: [ update_prs ]
